### ISSUE TITLE
2, 3 weeks expiry notifications

### ISSUE THREAD

**Issue by tomaslaz** [alan-turing-institute/rctab-api#39]
Please add a feature to notify users when a subscription is about to expire in 2 or 3 weeks. This will help users to take the necessary actions to renew their subscription.

**Comment by Iain-S** [comment]
Note for devs: [this](https://github.com/alan-turing-institute/rctab-api/blob/221bd6283c74168d5e9e7cf7912b2ccdc1b5c7d5/rctab/routers/accounting/send_emails.py#L389C27-L389C37) is the logic which determines the days on which expiry notifications are sent.
